from __future__ import annotations

import argparse
import csv
import re
import time
from pathlib import Path
from urllib.parse import urljoin, urlparse

from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError

BASE = "https://www.hetc.ac.in/"
DEFAULT_ARCHIVE = "https://www.hetc.ac.in/faculty/"
OUT_DIR = Path("references/hetc")
OUT_CSV = Path("refs.csv")
DEBUG_DIR = Path("output/hetc_debug")
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".gif"}
SKIP_TEXT = {
    "newer posts", "older posts", "next", "previous", "home", "read more",
    "faculty", "faculty members", "faculty-member", "menu"
}


def clean_name(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def slugify(text: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]+", "_", text.lower()).strip("_") or "faculty"


def same_site(url: str) -> bool:
    return urlparse(url).netloc.lower() in {"hetc.ac.in", "www.hetc.ac.in"}


def is_profile(url: str) -> bool:
    if not same_site(url):
        return False
    path = urlparse(url).path.rstrip("/")
    return bool(re.fullmatch(r"/faculty/[^/]+", path, flags=re.I))


def normalize_url(href: str, base_url: str) -> str:
    return urljoin(base_url, href.split("#", 1)[0]).rstrip("/") + "/"


def save_debug(page, page_no: int) -> None:
    DEBUG_DIR.mkdir(parents=True, exist_ok=True)
    try:
        (DEBUG_DIR / f"archive_{page_no}.html").write_text(page.content(), encoding="utf-8")
    except Exception:
        pass


def profile_from_candidate(href: str, text: str) -> str | None:
    """Accept only real HETC faculty profile URLs, but allow query strings."""
    if not is_profile(href):
        return None
    if len(text) < 2 or text.lower() in SKIP_TEXT:
        return None
    return href.rstrip("/") + "/"


def discover_profiles(page, max_pages: int) -> list[str]:
    """Discover profile URLs from the rendered archive.

    The HETC page can contain navigation/menu links and content generated by a
    page builder. We inspect all rendered anchors, iframe documents, and the
    serialized DOM. We also follow pagination links rather than assuming a
    particular pagination URL format.
    """
    profiles: set[str] = set()
    pages_seen: set[str] = set()
    queue = [DEFAULT_ARCHIVE]

    while queue and len(pages_seen) < max_pages:
        url = queue.pop(0)
        if url in pages_seen:
            continue
        pages_seen.add(url)

        print(f"Scanning archive: {url}")
        try:
            page.goto(url, wait_until="networkidle", timeout=90000)
        except PlaywrightTimeoutError:
            print("  ! networkidle timed out; continuing with loaded page")
        page.wait_for_timeout(2500)

        try:
            save_debug(page, len(pages_seen))
        except Exception:
            pass

        before = len(profiles)

        def inspect_frame(frame):
            try:
                items = frame.locator("a[href]").evaluate_all("""
                    els => els.map(e => ({
                        href: e.href || '',
                        text: (e.innerText || e.textContent || '').trim()
                    }))
                """)
            except Exception:
                return

            for item in items:
                href = str(item.get("href") or "")
                text = clean_name(str(item.get("text") or ""))
                if not href:
                    continue
                candidate = normalize_url(href, url)

                profile = profile_from_candidate(candidate, text)
                if profile:
                    profiles.add(profile)
                    continue

                if same_site(candidate):
                    path = urlparse(candidate).path.rstrip("/")
                    if path == "/faculty" or re.fullmatch(r"/faculty/page/\d+", path, flags=re.I):
                        if candidate not in pages_seen and candidate not in queue:
                            queue.append(candidate)

        for frame in page.frames:
            inspect_frame(frame)

        # Serialized DOM fallback. Search for both absolute and relative URLs.
        try:
            html = page.content()
            patterns = [
                r'https?://(?:www\\.)?hetc\\.ac\\.in/faculty/[^"\'<>\\s?#]+',
                r'href=["\'](/faculty/[^"\'<>?#]+)',
            ]
            for pattern in patterns:
                for match in re.findall(pattern, html, flags=re.I):
                    raw = match if match.startswith("http") else urljoin(url, match)
                    candidate = normalize_url(raw, url)
                    if is_profile(candidate):
                        profiles.add(candidate)
        except Exception:
            pass

        print(f"  + {len(profiles) - before} profile links found")

    if not profiles:
        print(f"  ! No profiles discovered. Debug HTML saved to {DEBUG_DIR}")

    return sorted(profiles)


def clean_title_name(text: str) -> str:
    text = clean_name(text)
    # Remove common site suffixes while preserving academic prefixes/titles.
    text = re.sub(
        r"\s*[-|–—:]\s*(Home|HETC|Halder College|Halder Technology and Engineering College|Halder Group).*$",
        "",
        text,
        flags=re.I,
    )
    return clean_name(text)


def choose_profile_image(page, profile_url: str) -> str | None:
    # Metadata is preferred because it is usually the profile's featured image.
    selectors = [
        'meta[property="og:image"]',
        'meta[property="og:image:url"]',
        'meta[name="twitter:image"]',
        'meta[name="twitter:image:src"]',
    ]
    for selector in selectors:
        loc = page.locator(selector)
        try:
            count = loc.count()
        except Exception:
            count = 0
        if count:
            value = loc.first.get_attribute("content")
            if value:
                candidate = urljoin(profile_url, value.strip())
                if same_site(candidate):
                    return candidate

    try:
        images = page.locator("img").evaluate_all("""
            els => els.map(e => ({
                src: e.currentSrc || e.src || e.getAttribute('data-src') || e.getAttribute('data-lazy-src') || '',
                alt: e.alt || '',
                w: e.naturalWidth || 0,
                h: e.naturalHeight || 0
            }))
        """)
    except Exception:
        images = []

    candidates: list[tuple[int, str]] = []
    for item in images:
        src = str(item.get("src") or "")
        if not src or not same_site(src):
            continue
        low = src.lower()
        if any(token in low for token in ("logo", "icon", "banner", "slider", "favicon", "header")):
            continue
        ext = Path(urlparse(src).path).suffix.lower()
        if ext not in IMAGE_EXTS:
            continue
        area = int(item.get("w") or 0) * int(item.get("h") or 0)
        candidates.append((max(area, 1), src))

    if candidates:
        return max(candidates)[1]

    return None


def extract_profile(page, profile_url: str) -> tuple[str | None, str | None]:
    try:
        page.goto(profile_url, wait_until="networkidle", timeout=90000)
    except PlaywrightTimeoutError:
        print("  ! profile networkidle timed out; continuing")
    page.wait_for_timeout(1500)

    name = None
    for selector in ("h1", ".entry-title", ".page-title", "article h2", "article h3"):
        try:
            loc = page.locator(selector)
            if loc.count():
                value = clean_title_name(loc.first.inner_text())
                if value:
                    name = value
                    break
        except Exception:
            pass

    if not name:
        try:
            name = clean_title_name(page.title())
        except Exception:
            pass

    image_url = choose_profile_image(page, profile_url)
    return name, image_url


def download(page, image_url: str, output: Path) -> bool:
    try:
        response = page.request.get(image_url, timeout=60000)
        if not response.ok:
            print(f"    ! HTTP {response.status} for image")
            return False
        body = response.body()
        if not body:
            return False
        ctype = (response.headers.get("content-type") or "").lower()
        if ctype and not ctype.startswith("image/"):
            print(f"    ! Not an image response: {ctype}")
            return False
        output.write_bytes(body)
        return True
    except Exception as exc:
        print(f"    ! Download failed: {exc}")
        return False


def main() -> None:
    parser = argparse.ArgumentParser(description="Collect HETC public faculty names and official profile photos.")
    parser.add_argument("--max-pages", type=int, default=7)
    parser.add_argument("--delay", type=float, default=0.5)
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    DEBUG_DIR.mkdir(parents=True, exist_ok=True)

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(
            viewport={"width": 1440, "height": 1200},
            locale="en-US",
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/131.0 Safari/537.36"
            ),
        )
        page = context.new_page()
        profiles = discover_profiles(page, args.max_pages)
        print(f"\nFound {len(profiles)} faculty profile URLs.\n")

        rows: list[tuple[str, str]] = []
        used: set[str] = set()

        for i, profile_url in enumerate(profiles, 1):
            print(f"[{i}/{len(profiles)}] {profile_url}")
            name, image_url = extract_profile(page, profile_url)
            if not name:
                print("  ! No faculty name found; skipping")
                continue
            print(f"  name: {name}")
            if not image_url:
                print("  ! No suitable image found; skipping")
                continue
            print(f"  image: {image_url}")

            slug = slugify(name)
            base = slug
            n = 2
            while slug in used:
                slug = f"{base}_{n}"
                n += 1
            used.add(slug)

            ext = Path(urlparse(image_url).path).suffix.lower()
            if ext not in IMAGE_EXTS:
                ext = ".jpg"
            output = OUT_DIR / f"{slug}{ext}"
            if download(page, image_url, output):
                rows.append((name, output.as_posix()))
                print(f"  saved: {output}")
            else:
                print("  ! Could not download image")
            time.sleep(args.delay)

        context.close()
        browser.close()

    with OUT_CSV.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(["name", "image"])
        writer.writerows(rows)

    print(f"\nImported {len(rows)} reference photos.")
    print(f"CSV: {OUT_CSV}")
    print(f"Images: {OUT_DIR}")
    print("Review refs.csv before using the references locally.")


if __name__ == "__main__":
    main()
